version: '3'

services:

  neo4j:
    container_name: scumsnet_neo
    image: augeas/scumsnet-neo4j
    ports:
     - "7474:7474"
     - "7473:7473"
     - "7687:7687"
    environment:
     - NEO4J_AUTH=none
     
  scumsnet:
    container_name: scumsnet
    image: augeas/scumsnet
    ports:
     - "5000:5000"
     - "6800:6800"
     - "8889:8888"
    depends_on:
     - neo4j
     

